server:
  port: 8082

spring:
  application:
    name: kafka-comsumer-service

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: demo-group

application:
  kafka:
    topic-name: demo-topic

